# environment.yaml

name: scRNA_pipeline
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - snakemake
  - fastqc
  - star
  - umi_tools
  - gzip
  - python=3.8
  - pandas
  - numpy
  - biopython

